name: d4_time_format
version: 1.0.0
description: Parse and format times, inspired by strptime and strftime.
repository: https://github.com/luizbarboza/d4_time_format

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  d4_array: ^1.0.0
  d4_time: ^1.0.0

dev_dependencies:
  lints: ^2.1.1
  test: ^1.22.0